import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1755624412716 implements MigrationInterface {
    name = 'AutoMigration1755624412716'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "submissions_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "assignments_teacher_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "assignments_course_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "assignments_class_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "attendance_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_teacher_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_subject_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_age_group_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attendance_class"`);
        await queryRunner.query(`DROP INDEX "public"."idx_enrollments_class"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_is_read"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_status"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "submissions_assignment_id_student_id_key"`);
        await queryRunner.query(`CREATE TABLE "class_sessions" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text, "scheduledStart" TIMESTAMP NOT NULL, "scheduledEnd" TIMESTAMP NOT NULL, "zoomMeetingId" character varying(100), "zoomJoinUrl" character varying(500), "zoomPassword" character varying(100), "status" character varying(50) NOT NULL DEFAULT 'scheduled', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" integer NOT NULL, CONSTRAINT "PK_dc034da48c6e0cf95c51f606c4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "content" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text, "contentType" character varying(50) NOT NULL DEFAULT 'text', "fileUrl" character varying(500), "durationMinutes" integer, "orderIndex" integer NOT NULL DEFAULT '0', "isPublic" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" integer NOT NULL, CONSTRAINT "PK_6a2083913f3647b44f205204e36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_students" ("id" SERIAL NOT NULL, "studentId" integer, "groupId" integer, CONSTRAINT "PK_cd596d1c8176853f748dc44af4b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "teacherId" integer NOT NULL, CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "assignment_id"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "file_url"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "score"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "submitted_at"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "course_id"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "class_id"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "instructions"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "due_date"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "max_score"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "file_path"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "class_id"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "recorded_at"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "subject_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "age_group_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "duration_weeks"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "max_students"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_pkey"`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_pkey" PRIMARY KEY ("class_id")`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_pkey"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "class_id"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "enrolled_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "is_read"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "action_url"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP CONSTRAINT "parents_pkey"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."user_status"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profile_picture"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emergency_contact"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "two_factor_enabled"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "two_factor_secret"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "temporary_access_code"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "access_code_expires_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verification_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_reset_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_reset_expires"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "submissionText" text`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "fileUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "submittedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "grade" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "gradedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "assignmentId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "studentId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "gradedById" integer`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "dueDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "maxPoints" numeric(5,2) NOT NULL DEFAULT '100'`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "assignmentType" character varying(50) NOT NULL DEFAULT 'homework'`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "courseId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "createdById" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "joinTime" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "leaveTime" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "sessionId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "studentId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "durationWeeks" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "maxStudents" integer NOT NULL DEFAULT '30'`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "difficultyLevel" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "prerequisites" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "enrollmentStartDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "enrollmentEndDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "instructorId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "enrollmentDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."enrollments_status_enum" AS ENUM('active', 'completed', 'dropped', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "status" "public"."enrollments_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "progressPercentage" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "finalGrade" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "studentId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "courseId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "content" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "notificationType" character varying(50) NOT NULL DEFAULT 'info'`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "isRead" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "actionUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parents" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parents" ADD CONSTRAINT "PK_9a4dc67c7b8e6a9cb918938d353" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "parents" ADD "parentId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parents" ADD "childId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parents" ADD "childAge" integer`);
        await queryRunner.query(`ALTER TABLE "parents" ADD "paymentInfo" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "passwordHash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "dateOfBirth" date`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profileImageUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastLogin" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "submissions_pkey"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "attendance_pkey"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status"`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "status" character varying(20) NOT NULL DEFAULT 'absent'`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'teacher', 'student', 'parent')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'student'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'student'`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_c2611c601f49945ceff5c0909a2" FOREIGN KEY ("assignmentId") REFERENCES "assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_4fc99318a291abd7e2a50f50851" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_5c97623fcf11b874808e3675195" FOREIGN KEY ("gradedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_9e5684667ea189ade0fc79fa4f1" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_d70609c9c9d978514fefe5999ac" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_4b3ed2a2a22881087475bc2e597" FOREIGN KEY ("sessionId") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_120e1c6edcec4f8221f467c8039" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "FK_276ed9a28f71990307723f15051" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content" ADD CONSTRAINT "FK_26bec3f34483ed6845c678dcde2" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_e6714597bea722629fa7d32124a" FOREIGN KEY ("instructorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_bf3ba3dfa95e2df7388eb4589fd" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_60dd0ae4e21002e63a5fdefeec8" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_students" ADD CONSTRAINT "FK_673797eb80fe17fe53d74ae049b" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_students" ADD CONSTRAINT "FK_db9a438a218989ecaa69acc225e" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_e63173ac43b478c2fc0cc20ac39" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parents" ADD CONSTRAINT "FK_88db7b24524eb2d732f433d46d4" FOREIGN KEY ("parentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parents" ADD CONSTRAINT "FK_c661280317e288a7a9eea648529" FOREIGN KEY ("childId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "parents" DROP CONSTRAINT "FK_c661280317e288a7a9eea648529"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP CONSTRAINT "FK_88db7b24524eb2d732f433d46d4"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_e63173ac43b478c2fc0cc20ac39"`);
        await queryRunner.query(`ALTER TABLE "group_students" DROP CONSTRAINT "FK_db9a438a218989ecaa69acc225e"`);
        await queryRunner.query(`ALTER TABLE "group_students" DROP CONSTRAINT "FK_673797eb80fe17fe53d74ae049b"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_60dd0ae4e21002e63a5fdefeec8"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_bf3ba3dfa95e2df7388eb4589fd"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_e6714597bea722629fa7d32124a"`);
        await queryRunner.query(`ALTER TABLE "content" DROP CONSTRAINT "FK_26bec3f34483ed6845c678dcde2"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "FK_276ed9a28f71990307723f15051"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_120e1c6edcec4f8221f467c8039"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_4b3ed2a2a22881087475bc2e597"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_d70609c9c9d978514fefe5999ac"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_9e5684667ea189ade0fc79fa4f1"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_5c97623fcf11b874808e3675195"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_4fc99318a291abd7e2a50f50851"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_c2611c601f49945ceff5c0909a2"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('student', 'teacher', 'parent', 'admin', 'financial_officer', 'educational_supervisor', 'technical_support')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "title" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "price" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "title" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status" AS ENUM('PRESENT', 'ABSENT', 'LATE')`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "status" "public"."attendance_status" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "attendance_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "title" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "submissions_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastLogin"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profileImageUrl"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "dateOfBirth"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "passwordHash"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP COLUMN "paymentInfo"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP COLUMN "childAge"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP COLUMN "childId"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP COLUMN "parentId"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP CONSTRAINT "PK_9a4dc67c7b8e6a9cb918938d353"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "actionUrl"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "isRead"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "notificationType"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "courseId"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "studentId"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "finalGrade"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "progressPercentage"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."enrollments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "enrollmentDate"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "instructorId"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "enrollmentEndDate"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "enrollmentStartDate"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "prerequisites"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "difficultyLevel"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "maxStudents"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "durationWeeks"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "studentId"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "leaveTime"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "joinTime"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "courseId"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "assignmentType"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "maxPoints"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "dueDate"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "gradedById"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "studentId"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "assignmentId"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "gradedAt"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "grade"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "submittedAt"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "fileUrl"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP COLUMN "submissionText"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_reset_expires" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_reset_token" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verification_token" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verified" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "access_code_expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "temporary_access_code" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "two_factor_secret" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "two_factor_enabled" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emergency_contact" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profile_picture" character varying(255)`);
        await queryRunner.query(`CREATE TYPE "public"."user_status" AS ENUM('active', 'inactive', 'suspended', 'pending')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."user_status" DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "gender" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "date_of_birth" date`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "parents" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "parents" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parents" ADD CONSTRAINT "parents_pkey" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "action_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "is_read" boolean DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type" AS ENUM('info', 'warning', 'success', 'error')`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" "public"."notification_type" DEFAULT 'info'`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "message" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "enrolled_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "class_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_pkey" PRIMARY KEY ("class_id")`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_pkey"`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_pkey" PRIMARY KEY ("student_id", "class_id")`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "is_active" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "max_students" integer DEFAULT '20'`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "duration_weeks" integer DEFAULT '12'`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "teacher_id" integer`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "age_group_id" integer`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "subject_id" integer`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "recorded_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "student_id" uuid`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "class_id" uuid`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "is_active" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "file_path" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "max_score" numeric(5,2) DEFAULT 100.00`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "due_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "instructions" text`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "teacher_id" integer`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "class_id" integer`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "course_id" integer`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "submitted_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "score" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "file_url" text`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "student_id" uuid`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD "assignment_id" uuid`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TABLE "group_students"`);
        await queryRunner.query(`DROP TABLE "content"`);
        await queryRunner.query(`DROP TABLE "class_sessions"`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "submissions_assignment_id_student_id_key" UNIQUE ("assignment_id", "student_id")`);
        await queryRunner.query(`CREATE INDEX "idx_users_status" ON "users" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_is_read" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_id" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_enrollments_class" ON "enrollments" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "idx_attendance_class" ON "attendance" ("class_id") `);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_age_group_id_fkey" FOREIGN KEY ("age_group_id") REFERENCES "age_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "attendance_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "assignments_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "assignments_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "assignments_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "submissions_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
